force-app/main/default/objects/Archived_Case__b/Archived_Case__b.object-meta.xml
<CustomObject>
    <label>Archived Case</label>
    <pluralLabel>Archived Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Archived_Case__b/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archived_Case__b/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archived_Case__b/fields/Date_Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Closed__c</fullName>
    <label>Date/Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Archived_Case__b/fields/Date_Time_Opened__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Opened__c</fullName>
    <label>Date/Time Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Archived_Case__b/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountArchivedCasesController.cls
public with sharing class AccountArchivedCasesController {
    @AuraEnabled(cacheable=true)
    public static List<Archived_Case__b> getArchivedCases(Id accountId) {
        List<Archived_Case__b> archivedCases = new List<Archived_Case__b>();
        try {
            archivedCases = [SELECT Case_Number__c, Subject__c, Type__c, Date_Time_Closed__c, Date_Time_Opened__c 
                FROM Archived_Case__b 
                WHERE Account_Id__c = :accountId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return archivedCases;
    }
}